apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-dev
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
      service.alpha.openshift.io/dependencies: '[]'
    creationTimestamp: null
    labels:
      app: prov-app
      branch: feature
      component: prov-app
      env: dev
      template: component-template
    name: prov-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: prov-app
      component: prov-app
      deploymentconfig: prov-app
      env: dev
    sessionAffinity: None
    type: ClusterIP
