apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-cd
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: jenkins
      template: component-pipeline
    name: prov-app-dev
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: production
        uri: ${PROV_APP_REPO_URL}
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - generic:
        secret: secret101
      type: Generic
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: jenkins
      template: component-pipeline
    name: prov-app-test
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: production
        uri: ${PROV_APP_REPO_URL}
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - generic:
        secret: secret101
      type: Generic
parameters:
- name: PROV_APP_REPO_URL
  required: true
