apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-cd
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: jenkins
      template: cd-jenkins-persistent-template
    name: jenkins_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: prov-cd
  userNames:
  - system:serviceaccount:prov-cd:jenkins
