apiVersion: v1
kind: Template
parameters:
- name: PROJECT
  required: true
- name: COMPONENT
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PROJECT}-${COMPONENT}
    name: ${COMPONENT}
  spec:
    nodeSelector: null
    output:
      imageLabels:
      - name: "ods.application.name"
        value: "Provisioning application"
      to:
        kind: ImageStreamTag
        name: ${COMPONENT}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
