apiVersion: v1
kind: Template
parameters:
- name: PROJECT
  required: true
- name: COMPONENT
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${PROJECT}-${COMPONENT}
    name: ${COMPONENT}
  spec:
    lookupPolicy:
      local: false
