apiVersion: v1
kind: Template
parameters:
- name: ODS_IMAGE_TAG
  required: true
- name: ODS_GIT_REF
  required: true
- name: JIRA_URL
  required: true
  description: the URI of JIRA used to create new jira projects
- name: CONFLUENCE_URL
  required: true
  description: the URI of confluence used to create new confluence spaces
- name: BITBUCKET_URL
  required: true
  description: the URI of bitbucket used to create new project and repositories
- name: CROWD_URL
  required: true
  description: the URI of crowd used to authenticate users from the app against
- name: OPENSHIFT_CONSOLE_HOST
  required: true
  description: the console host of the OCP cluster
- name: PROV_APP_CROWD_USER_GROUP
  required: true
  description: crowd user group
- name: CD_USER_ID
  required: true
  description: the username of the CD user
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
  description: the domain of routes exposed on OCP
- name: PROV_APP_PACKAGE_PREFIX
  required: true
  description: the default package prefix
- name: PROV_APP_ATLASSIAN_DOMAIN
  required: true
  description: the domain of the atlassian toolsuite needed for single signon cookies
- name: PROV_APP_CROWD_PASSWORD
  required: true
  description: password of the crowd app to authenticate the provision app against
- name: PROV_APP_JASYPT_PASSWORD
  required: true
- name: PROV_APP_MAIL_HOST
  required: true
  description: The hostname of the mailserver
- name: PROV_APP_MAIL_PASSWORD
  required: true
  description: The password to authenticate against the mail server
- name: PROV_APP_MAIL_USERNAME
  required: true
  description: The username to authenticate against the mail server
- name: PROV_APP_CROWD_ADMIN_GROUP
  required: true
  description: The crowd admin group name
- name: PROV_APP_PIPELINE_TRIGGER_SECRET
  required: true
  description: The trigger secret to pass to the webhook proxy
- name: PROV_APP_LOG_LEVEL_ATLASSIAN_CROWD
  required: true
  description: Log level of Atlassian crowd package
- name: PROV_APP_LOG_LEVEL_OPENDEVSTACK
  required: true
  description: Log level of OpenDevStack package
- name: LOGGING_FILE_PATH
  required: true
  description: File system location for the log files
- name: READABLE_OPENDEVSTACK_REPOS
  required: true
  description: Repositories which the project specific technical user can read
- name: WEBHOOK_PROXY_EVENTS
  required: true
  description: list of supported webhook events
- name: PROV_APP_WEBHOOKPROXY_HOST
  required: true
  description: the webhookproxy host that prov app connect to
objects:
- kind: ConfigMap
  metadata:
    labels:
      app: prov-app
    name: application.properties
  apiVersion: v1
  data:
    properties: |
      # log level
      logging.level.com.atlassian.crowd=${PROV_APP_LOG_LEVEL_ATLASSIAN_CROWD}
      logging.level.org.opendevstack=${PROV_APP_LOG_LEVEL_OPENDEVSTACK}

      # log file
      logging.file.path=${LOGGING_FILE_PATH}

      # atlassian API calls take sooo long
      global.keyuser.role.name=${idmanager.group.opendevstack-administrators}

      # JIRA properties
      jira.uri=${JIRA_URL}

      # Confluence properties
      confluence.uri=${CONFLUENCE_URL}

      # Bitbucket properties
      bitbucket.uri=${BITBUCKET_URL}
      bitbucket.default.user.group=${PROV_APP_CROWD_USER_GROUP}
      bitbucket.technical.user=${CD_USER_ID}

      scm.global.readablerepos.opendevstack=${READABLE_OPENDEVSTACK_REPOS}

      # ODS properties
      ods.image-tag=${ODS_IMAGE_TAG}
      ods.git-ref=${ODS_GIT_REF}

      # openshift properties
      openshift.apps.basedomain=${OPENSHIFT_APPS_BASEDOMAIN}
      openshift.console.uri=${OPENSHIFT_CONSOLE_HOST}/console/project/

      # the webhook proxy that proxies to the jenkins instance that creates and deletes projects. Usually you have one
      # webhook proxy of this kind in an ods installation residing in the ods namespace.
      openshift.jenkins.admin.webhookproxy.host=${PROV_APP_WEBHOOKPROXY_HOST}

      # list of supported webhook events
      openshift.jenkins.project.webhookproxy.events=${WEBHOOK_PROXY_EVENTS}

      openshift.jenkins.trigger.secret=${PROV_APP_PIPELINE_TRIGGER_SECRET}

      artifact.group.pattern=${PROV_APP_PACKAGE_PREFIX}.%s

      # Cookie Domain
      atlassian.domain=${PROV_APP_ATLASSIAN_DOMAIN}

      # idmanager
      idmanager.group.opendevstack-users=${PROV_APP_CROWD_USER_GROUP}
      idmanager.group.opendevstack-administrators=${PROV_APP_CROWD_ADMIN_GROUP}

      # crowd properties
      crowd.application.password=${PROV_APP_CROWD_PASSWORD}
      crowd.server.url=${CROWD_URL}/services/
      crowd.cookie.domain=${OPENSHIFT_APPS_BASEDOMAIN}

      jasypt.encryptor.password=${PROV_APP_JASYPT_PASSWORD}

      spring.mail.host=${PROV_APP_MAIL_HOST}
      spring.mail.username=${PROV_APP_MAIL_USERNAME}
      spring.mail.password=${PROV_APP_MAIL_PASSWORD}
      provison.mail.sender=provision@${PROV_APP_MAIL_HOST}
