apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-test
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    creationTimestamp: null
    labels:
      app: prov-app
      component: prov-app
      env: test
      template: component-template
    name: prov-app
  spec:
    dockerImageRepository: prov-app
    lookupPolicy:
      local: false
